#!/usr/bin/python3
from sys import argv
from math import sqrt
import math

def factor(number, test_num):
	#Finds the values to return once a number has been found
	prints("{}={}*{}".format(number, (number // test_num), test_num))

with open(argv[1], mode="r", encoding="UTF-8") as f:
	for line in f:
		number = int(line)
		if number % 2 == 0:
			factor(number, 2)
		else:
		
