#!/usr/bin/python3
from sys import argv
"""
Factorize as many numbers as possible into a product of two smaller numbers.
    Usage: factors <file>
        where <file> is a file containg natural numbers to factor.
        One number per line
        You can assume that all lines will be valid natural numbers\
                greater than 1
        You can assume that there will be no empty line , and no space\
                before and after the valid number
        The file will always end with a new line
    Output format: n=p*q
        one factorization per line
        p and q don't have to be prime numbers
        see example
    You can work on the numbers of the file in the order of your choice
    Your program should run without any dependency: You will not be able\
            to install anything on the machine we will run your program on
    Time limit: your program will be killed after 5 seconds\
            if it hasn't finished
    push all your scripts, source code,etc,,, to yor repository
"""

""" Class factor_file """

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end="")
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for i in range(3, num, 2):
            if num % 1 == 0:
                factor = num//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or i % j == 0:
                        break
                    print("{}*{}".format(factor, i))
                    break
